import { CopyOutlined, EditOutlined, ExportOutlined, ReloadOutlined, SafetyCertificateOutlined } from '@ant-design/icons';
import type { ProColumns } from '@ant-design/pro-components';
import { Button, Card, Descriptions, Drawer, Form, Input, Select, Space, Spin, Switch, Tabs, Tag, Typography } from 'antd';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { getLocale } from '@umijs/max';
import { ManagementPage } from '@/features/management/ManagementPage';
import { ManagementPageBody } from '@/features/management/ManagementPageBody';
import { ManagementTable } from '@/features/management/ManagementTable';
import { usePagePermissionActions } from '@/features/permissions/usePagePermissionActions';
import { normalizeLocale } from '@/i18n/locale';
import { request } from '@/services/common/request';
import { message } from '@/theme/antdFeedbackBridge';
import { API_OPTS, showErrorMessage } from '@/utils/errorMessage';

type FieldControl =
  | 'system-id'
  | 'input'
  | 'textarea'
  | 'segmented'
  | 'select'
  | 'switch'
  | 'image-url-or-upload'
  | 'icon-select'
  | 'drag-sort-number'
  | 'publish-switch'
  | 'tag-input'
  | 'field-group'
  | 'schema-driven-extra'
  | 'route-or-url-input'
  | 'markdown-editor';

interface AiadcField {
  sectionKey: string;
  sectionLabel: string;
  permission: string;
  pageKey?: string;
  collection?: string;
  area?: string;
  sectionCode?: string;
  path: string;
  type: string;
  control: FieldControl;
  required: boolean;
  editable: boolean;
  guarded?: boolean;
  note?: string;
}

interface AiadcSectionSummary {
  key: string;
  label: string;
  fieldCount: number;
  publishedCount: number;
}

interface AiadcFieldApiRecord extends Omit<AiadcField, 'type' | 'control'> {
  fieldType: string;
  controlType: FieldControl;
  draftValue?: string;
  publishedValue?: string;
  updatedAt?: string;
  publishedAt?: string;
  version?: number;
}

interface PagedFields {
  records: AiadcFieldApiRecord[];
  total: number;
}

interface BusinessRecord {
  pageKey?: string;
  collection?: string;
  area?: string;
  sectionCode?: string;
  fields: Array<Omit<AiadcField, 'sectionKey' | 'sectionLabel' | 'permission' | 'pageKey' | 'collection' | 'area' | 'sectionCode'>>;
}

interface BusinessSection {
  key: string;
  label: string;
  description: string;
  permissionPrefix: string;
  records: BusinessRecord[];
}

const isEnglishLocale = () => normalizeLocale(getLocale()) === 'en-US';
const t = (zh: string, en: string) => (isEnglishLocale() ? en : zh);

const baseRecordFields: BusinessRecord['fields'] = [
  { path: 'id', type: 'string', control: 'system-id', required: true, editable: false, note: 'Generated by system' },
  { path: 'code', type: 'string', control: 'input', required: true, editable: true, guarded: true, note: 'Stable business key' },
  { path: 'locale', type: 'zh | en', control: 'segmented', required: true, editable: true },
  { path: 'title', type: 'string', control: 'input', required: true, editable: true },
  { path: 'subtitle', type: 'string', control: 'input', required: false, editable: true },
  { path: 'description', type: 'string', control: 'textarea', required: false, editable: true },
  { path: 'imageUrl', type: 'url', control: 'image-url-or-upload', required: false, editable: true },
  { path: 'iconKey', type: 'string', control: 'icon-select', required: false, editable: true },
  { path: 'sort', type: 'number', control: 'drag-sort-number', required: true, editable: true },
  { path: 'status', type: 'draft | published', control: 'publish-switch', required: true, editable: true },
  { path: 'tags', type: 'string[]', control: 'tag-input', required: false, editable: true },
  { path: 'cta.label', type: 'string', control: 'input', required: false, editable: true },
  { path: 'cta.href', type: 'string', control: 'route-or-url-input', required: false, editable: true },
  { path: 'badge.text', type: 'string', control: 'input', required: false, editable: true },
  { path: 'badge.tone', type: 'blue | gold | silver | bronze | slate | dark', control: 'select', required: false, editable: true },
];

const heroFields: BusinessRecord['fields'] = [
  { path: 'hero.eyebrow', type: 'string', control: 'input', required: true, editable: true },
  { path: 'hero.title', type: 'string', control: 'input', required: true, editable: true },
  { path: 'hero.description', type: 'string', control: 'textarea', required: true, editable: true },
  { path: 'hero.backgroundImage', type: 'url', control: 'image-url-or-upload', required: false, editable: true },
  { path: 'hero.dark', type: 'boolean', control: 'switch', required: false, editable: true },
  { path: 'seo.title', type: 'string', control: 'input', required: true, editable: true },
  { path: 'seo.description', type: 'string', control: 'textarea', required: true, editable: true },
];

const linkActionFields: BusinessRecord['fields'] = [
  { path: 'label', type: 'string', control: 'input', required: true, editable: true },
  { path: 'href', type: 'string', control: 'route-or-url-input', required: true, editable: true },
  { path: 'target', type: '_self | _blank', control: 'select', required: false, editable: true },
  { path: 'variant', type: 'primary | secondary | ghost | outline | link', control: 'select', required: false, editable: true },
];

const sections: BusinessSection[] = [
  {
    key: 'competition-promotion',
    label: 'Competition promotion',
    description: 'Home hero, carousel, stats, participant groups, highlights, partners, and FAQ.',
    permissionPrefix: 'aiadc:cms:promotion',
    records: [
      { pageKey: 'home', area: 'hero', fields: heroFields },
      {
        pageKey: 'home',
        sectionCode: 'heroSlides',
        fields: [
          ...baseRecordFields,
          { path: 'extra.alt', type: 'string', control: 'input', required: true, editable: true },
          { path: 'extra.accent', type: 'string', control: 'input', required: false, editable: true },
          { path: 'extra.deadline', type: 'string', control: 'input', required: false, editable: true },
        ],
      },
      { pageKey: 'home', sectionCode: 'stats', fields: [...baseRecordFields, { path: 'value', type: 'string', control: 'input', required: true, editable: true }, { path: 'label', type: 'string', control: 'input', required: true, editable: true }] },
      { pageKey: 'home', sectionCode: 'groups', fields: baseRecordFields },
      { pageKey: 'home', sectionCode: 'highlights', fields: baseRecordFields },
      { pageKey: 'home', sectionCode: 'partners', fields: baseRecordFields },
      { pageKey: 'home', sectionCode: 'faq', fields: baseRecordFields },
    ],
  },
  {
    key: 'competition-registration',
    label: 'Competition registration',
    description: 'Registration CTA, track requirements, downloadable materials, and login entry.',
    permissionPrefix: 'aiadc:cms:registration',
    records: [
      {
        pageKey: 'home',
        area: 'ctaBanner',
        fields: [
          { path: 'kicker', type: 'string', control: 'input', required: false, editable: true },
          { path: 'title', type: 'string', control: 'input', required: true, editable: true },
          { path: 'description', type: 'string', control: 'textarea', required: false, editable: true },
          { path: 'action.label', type: 'string', control: 'input', required: true, editable: true },
          { path: 'action.href', type: 'string', control: 'route-or-url-input', required: true, editable: true },
        ],
      },
      { pageKey: 'intro', sectionCode: 'tracks', fields: [...baseRecordFields, { path: 'extra.badge', type: 'string', control: 'input', required: false, editable: true }] },
      { pageKey: 'materials', sectionCode: 'materials', fields: [...baseRecordFields, { path: 'format', type: 'string', control: 'input', required: true, editable: true }, { path: 'audience', type: 'string', control: 'input', required: true, editable: true }, { path: 'actionLabel', type: 'string', control: 'input', required: true, editable: true }, { path: 'fileUrl', type: 'url', control: 'route-or-url-input', required: true, editable: true }] },
      { pageKey: 'login', area: 'primaryAction', fields: linkActionFields },
    ],
  },
  {
    key: 'competition-intro',
    label: 'Competition introduction',
    description: 'Competition overview, value cards, schedule, awards, tracks, and contacts.',
    permissionPrefix: 'aiadc:cms:intro',
    records: [
      { pageKey: 'intro', area: 'hero', fields: heroFields },
      { pageKey: 'intro', sectionCode: 'valueCards', fields: baseRecordFields },
      { pageKey: 'intro', sectionCode: 'schedule', fields: [...baseRecordFields, { path: 'date', type: 'string', control: 'input', required: true, editable: true }, { path: 'detail', type: 'string', control: 'textarea', required: true, editable: true }, { path: 'featured', type: 'boolean', control: 'switch', required: false, editable: true }] },
      { pageKey: 'intro', sectionCode: 'awards', fields: [...baseRecordFields, { path: 'extra.prize', type: 'string', control: 'input', required: true, editable: true }, { path: 'extra.tone', type: 'gold | silver | bronze | slate', control: 'select', required: false, editable: true }, { path: 'extra.glyph', type: 'string', control: 'input', required: false, editable: true }] },
      { pageKey: 'intro', sectionCode: 'contacts', fields: baseRecordFields },
    ],
  },
  {
    key: 'activities',
    label: 'Activities',
    description: 'Activity filters and event cards with date, time, location, and featured status.',
    permissionPrefix: 'aiadc:cms:events',
    records: [
      { pageKey: 'events', area: 'hero', fields: heroFields },
      { pageKey: 'events', sectionCode: 'filters', fields: baseRecordFields },
      { pageKey: 'events', sectionCode: 'events', fields: [...baseRecordFields, { path: 'extra.date', type: 'string', control: 'input', required: true, editable: true }, { path: 'extra.time', type: 'string', control: 'input', required: true, editable: true }, { path: 'extra.location', type: 'string', control: 'input', required: true, editable: true }, { path: 'extra.featured', type: 'boolean', control: 'switch', required: false, editable: true }] },
    ],
  },
  {
    key: 'projects',
    label: 'Projects',
    description: 'Featured projects, filters, stats, tracks, stages, dates, and highlights.',
    permissionPrefix: 'aiadc:cms:projects',
    records: [
      { pageKey: 'projects', area: 'hero', fields: heroFields },
      { pageKey: 'projects', sectionCode: 'filters', fields: baseRecordFields },
      { pageKey: 'projects', sectionCode: 'stats', fields: [...baseRecordFields, { path: 'value', type: 'string', control: 'input', required: true, editable: true }, { path: 'label', type: 'string', control: 'input', required: true, editable: true }] },
      { pageKey: 'projects', sectionCode: 'projects', fields: [...baseRecordFields, { path: 'extra.track', type: 'string', control: 'input', required: true, editable: true }, { path: 'extra.stage', type: 'string', control: 'input', required: true, editable: true }, { path: 'extra.date', type: 'string', control: 'input', required: true, editable: true }, { path: 'extra.highlight', type: 'string', control: 'textarea', required: true, editable: true }, { path: 'extra.featured', type: 'boolean', control: 'switch', required: false, editable: true }] },
    ],
  },
  {
    key: 'startup-base',
    label: 'Startup base',
    description: 'Incubation spaces, resource matching, and growth support cards.',
    permissionPrefix: 'aiadc:cms:startup-base',
    records: [
      { pageKey: 'startup-base', area: 'hero', fields: heroFields },
      { pageKey: 'startup-base', sectionCode: 'baseItems', fields: [...baseRecordFields, { path: 'extra.location', type: 'string', control: 'input', required: true, editable: true }] },
    ],
  },
  {
    key: 'news',
    label: 'News',
    description: 'News page hero, categories, article list, article body, and publish status.',
    permissionPrefix: 'aiadc:cms:news',
    records: [
      { pageKey: 'news', area: 'hero', fields: heroFields },
      { collection: 'newsCategories', fields: [{ path: 'items', type: 'NewsCategorySummary[]', control: 'schema-driven-extra', required: true, editable: true, note: 'JSON array: [{ "label": "通知公告", "value": "notice", "description": "...", "sort": 1, "status": "published" }]' }] },
      { collection: 'newsArticles', fields: [{ path: 'items', type: 'ArticleItem[]', control: 'markdown-editor', required: true, editable: true, note: 'JSON array. Each article supports category, tags, slug, image, bodyMarkdown, contentFormat=markdown.' }] },
    ],
  },
  {
    key: 'site-settings',
    label: 'Site settings',
    description: 'Brand, navigation, footer, filings, and page SEO metadata.',
    permissionPrefix: 'aiadc:cms:site',
    records: [
      { collection: 'siteShell', fields: [{ path: 'brand.primary', type: 'string', control: 'input', required: true, editable: true }, { path: 'brand.secondary', type: 'string', control: 'input', required: true, editable: true }, { path: 'brand.homeAria', type: 'string', control: 'input', required: true, editable: true }, { path: 'brand.applicationName', type: 'string', control: 'input', required: true, editable: true }, { path: 'header.mainNavItems', type: 'NavLinkItem[]', control: 'field-group', required: true, editable: true }, { path: 'footer.columns', type: 'FooterColumn[]', control: 'field-group', required: true, editable: true }] },
      { collection: 'siteMeta', fields: heroFields.filter((field) => field.path.startsWith('seo.')) },
    ],
  },
  {
    key: 'legal-pages',
    label: 'Legal pages',
    description: 'Privacy policy and terms rich text blocks.',
    permissionPrefix: 'aiadc:cms:legal',
    records: [
      { pageKey: 'privacy', area: 'page', fields: [...heroFields, { path: 'richTextBlocks[].type', type: 'paragraph | markdown', control: 'select', required: true, editable: true }, { path: 'richTextBlocks[].content', type: 'string', control: 'markdown-editor', required: true, editable: true }] },
      { pageKey: 'terms', area: 'page', fields: [...heroFields, { path: 'richTextBlocks[].type', type: 'paragraph | markdown', control: 'select', required: true, editable: true }, { path: 'richTextBlocks[].content', type: 'string', control: 'markdown-editor', required: true, editable: true }] },
    ],
  },
];

const fields = sections.flatMap((section) =>
  section.records.flatMap((record) =>
    record.fields.map((field) => ({
      ...field,
      sectionKey: section.key,
      sectionLabel: section.label,
      permission: `${section.permissionPrefix}:update`,
      pageKey: record.pageKey,
      collection: record.collection,
      area: record.area,
      sectionCode: record.sectionCode,
    })),
  ),
) satisfies AiadcField[];

const normalizeApiField = (field: AiadcFieldApiRecord): AiadcField => ({
  ...field,
  type: field.fieldType,
  control: field.controlType,
});

const renderControl = (control: FieldControl) => <Tag color={control.includes('switch') ? 'green' : control.includes('upload') ? 'blue' : 'default'}>{control}</Tag>;

const renderFieldEditor = (field: AiadcField) => {
  if (!field.editable) {
    return <Input disabled placeholder={field.path} />;
  }
  if (field.control === 'switch' || field.control === 'publish-switch') {
    return <Switch checkedChildren="on" unCheckedChildren="off" />;
  }
  if (field.control === 'textarea' || field.control === 'markdown-editor' || field.control === 'schema-driven-extra') {
    return <Input.TextArea rows={6} placeholder={field.path} />;
  }
  if (field.control === 'select' || field.control === 'segmented') {
    return (
      <Select
        placeholder={field.path}
        options={[
          { label: 'draft', value: 'draft' },
          { label: 'published', value: 'published' },
          { label: 'zh', value: 'zh' },
          { label: 'en', value: 'en' },
          { label: '_self', value: '_self' },
          { label: '_blank', value: '_blank' },
        ]}
      />
    );
  }
  return <Input placeholder={field.path} />;
};

const AiadcCmsPage = () => {
  const { actionPermission, responsive, searchConfig, buildToolbarButtons } = usePagePermissionActions();
  const [activeKey, setActiveKey] = useState(sections[0].key);
  const [editingField, setEditingField] = useState<AiadcField | null>(null);
  const [fieldForm] = Form.useForm<{ valueJson?: unknown }>();
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [serverSections, setServerSections] = useState<AiadcSectionSummary[]>([]);
  const [serverFields, setServerFields] = useState<AiadcField[]>([]);
  const displayedSections = serverSections.length
    ? serverSections.map((section) => sections.find((item) => item.key === section.key) || {
        key: section.key,
        label: section.label,
        description: `${section.fieldCount} fields, ${section.publishedCount} published`,
        permissionPrefix: `aiadc:cms:${section.key}`,
        records: [],
      })
    : sections;
  const activeSection = displayedSections.find((section) => section.key === activeKey) || displayedSections[0] || sections[0];
  const allFields = serverFields.length ? serverFields : fields;
  const activeFields = useMemo(() => allFields.filter((field) => field.sectionKey === activeSection.key), [activeSection.key, allFields]);
  const totalEditableFields = allFields.filter((field) => field.editable).length;
  const guardedFields = allFields.filter((field) => field.guarded).length;

  const loadCmsFields = useCallback(async () => {
    setLoading(true);
    try {
      const [sectionResult, fieldResult] = await Promise.all([
        request<AiadcSectionSummary[]>('/v1/aiadc/cms/sections', {
          method: 'GET',
          ...API_OPTS.SILENT_NO_REDIRECT,
        }),
        request<PagedFields>('/v1/aiadc/cms/fields', {
          method: 'GET',
          params: { pageNo: 1, pageSize: 200 },
          ...API_OPTS.SILENT_NO_REDIRECT,
        }),
      ]);
      setServerSections(sectionResult);
      setServerFields((fieldResult.records || []).map(normalizeApiField));
      if (!sectionResult.some((section) => section.key === activeKey) && sectionResult[0]) {
        setActiveKey(sectionResult[0].key);
      }
    } catch (error) {
      setServerSections([]);
      setServerFields([]);
      showErrorMessage(error, t('AIADC CMS 后端暂不可用，已切换到本地字段契约', 'AIADC CMS backend is unavailable. Using the local field contract.'));
    } finally {
      setLoading(false);
    }
  }, [activeKey]);

  useEffect(() => {
    void loadCmsFields();
  }, [loadCmsFields]);

  const openEditor = useCallback(
    (field: AiadcField) => {
      setEditingField(field);
      const apiField = field as AiadcField & { draftValue?: string; publishedValue?: string };
      fieldForm.setFieldsValue({ valueJson: apiField.draftValue ?? apiField.publishedValue ?? '' });
    },
    [fieldForm],
  );

  const saveEditingField = useCallback(async () => {
    if (!editingField) {
      return;
    }
    setSaving(true);
    try {
      const values = await fieldForm.validateFields();
      await request<AiadcFieldApiRecord>('/v1/aiadc/cms/fields', {
        method: 'PUT',
        data: {
          sectionKey: editingField.sectionKey,
          pageKey: editingField.pageKey,
          collectionKey: editingField.collection,
          areaKey: editingField.area,
          sectionCode: editingField.sectionCode,
          fieldPath: editingField.path,
          valueJson: typeof values.valueJson === 'string' ? values.valueJson : JSON.stringify(values.valueJson ?? null),
        },
        ...API_OPTS.NO_REDIRECT,
      });
      message.success(t('字段草稿已保存', 'Field draft saved'));
      setEditingField(null);
      await loadCmsFields();
    } finally {
      setSaving(false);
    }
  }, [editingField, fieldForm, loadCmsFields]);

  const publishEditingField = useCallback(async () => {
    const id = (editingField as AiadcField & { id?: number } | null)?.id;
    if (!id) {
      message.warning(t('请先保存字段，再发布', 'Save the field before publishing'));
      return;
    }
    setSaving(true);
    try {
      await request<AiadcFieldApiRecord>(`/v1/aiadc/cms/fields/${id}/publish`, {
        method: 'POST',
        ...API_OPTS.NO_REDIRECT,
      });
      message.success(t('字段已发布', 'Field published'));
      setEditingField(null);
      await loadCmsFields();
    } finally {
      setSaving(false);
    }
  }, [editingField, loadCmsFields]);

  const columns = useMemo<ProColumns<AiadcField>[]>(
    () => [
      { title: t('板块', 'Section'), dataIndex: 'sectionLabel', hideInTable: true },
      { title: t('页面', 'Page'), dataIndex: 'pageKey', width: 110, renderText: (_, record) => record.pageKey || record.collection || '-' },
      { title: t('区域', 'Area'), dataIndex: 'sectionCode', width: 140, renderText: (_, record) => record.sectionCode || record.area || record.collection || '-' },
      { title: t('字段', 'Field'), dataIndex: 'path', ellipsis: true, render: (_, record) => <Typography.Text copyable={{ text: record.path }}>{record.path}</Typography.Text> },
      { title: t('类型', 'Type'), dataIndex: 'type', width: 160 },
      { title: t('控件', 'Control'), dataIndex: 'control', width: 180, render: (_, record) => renderControl(record.control) },
      { title: t('必填', 'Required'), dataIndex: 'required', width: 90, search: false, render: (_, record) => <Tag color={record.required ? 'red' : 'default'}>{record.required ? 'Yes' : 'No'}</Tag> },
      { title: t('可编辑', 'Editable'), dataIndex: 'editable', width: 90, search: false, render: (_, record) => <Tag color={record.editable ? 'green' : 'default'}>{record.editable ? 'Yes' : 'No'}</Tag> },
      {
        title: t('操作', 'Actions'),
        valueType: 'option',
        fixed: responsive.isDesktop ? 'right' : undefined,
        render: (_, record) => [
          <Button key="edit" type="link" size="small" icon={<EditOutlined />} disabled={!record.editable || !actionPermission.can(record.permission)} onClick={() => openEditor(record)}>
            {t('编辑', 'Edit')}
          </Button>,
        ],
      },
    ],
    [actionPermission, responsive.isDesktop],
  );

  return (
    <ManagementPage title={t('AIADC 内容中台', 'AIADC content management')} subTitle={t('独立业务系统字段契约', 'Independent business field contract')}>
      <ManagementPageBody>
        <Card>
          <Descriptions column={responsive.isMobile ? 1 : 4} size="small">
            <Descriptions.Item label={t('业务板块', 'Sections')}>{sections.length}</Descriptions.Item>
            <Descriptions.Item label={t('字段总数', 'Fields')}>{fields.length}</Descriptions.Item>
            <Descriptions.Item label={t('可编辑字段', 'Editable')}>{totalEditableFields}</Descriptions.Item>
            <Descriptions.Item label={t('受保护字段', 'Guarded')}>{guardedFields}</Descriptions.Item>
          </Descriptions>
          <Typography.Paragraph type="secondary" style={{ margin: '12px 0 0' }}>
            {t(
              '本页面按比赛宣传、比赛报名、活动、项目、新闻等板块组织 AIADC-WEB JSON 字段，写接口接入后可复用同一套表格、抽屉、权限和发布流程。',
              'This page groups the AIADC-WEB JSON fields by promotion, registration, activities, projects, news, and more. Backend APIs can reuse the same table, drawer, permission, and publish workflow.',
            )}
          </Typography.Paragraph>
        </Card>

        <Spin spinning={loading}>
        <Tabs
          activeKey={activeKey}
          onChange={setActiveKey}
          items={displayedSections.map((section) => ({
            key: section.key,
            label: section.label,
            children: (
              <Space direction="vertical" size="middle" style={{ width: '100%' }}>
                <Card size="small">
                  <Space direction="vertical" size={4}>
                    <Typography.Text strong>{section.description}</Typography.Text>
                    <Space wrap>
                      <Tag icon={<SafetyCertificateOutlined />} color={actionPermission.can(`${section.permissionPrefix}:update`) ? 'green' : 'orange'}>
                        {section.permissionPrefix}:update
                      </Tag>
                      <Tag>{section.records.length} records</Tag>
                      <Tag>{activeFields.length} fields</Tag>
                    </Space>
                  </Space>
                </Card>
                <ManagementTable<AiadcField>
                  rowKey={(record) => `${record.sectionKey}:${record.pageKey || record.collection}:${record.sectionCode || record.area}:${record.path}`}
                  columns={columns}
                  isMobile={responsive.isMobile}
                  search={searchConfig}
                  dataSource={activeFields}
                  pagination={{ pageSize: 12, showSizeChanger: true }}
                  toolBarRender={() =>
                    buildToolbarButtons([
                      { key: 'refresh', label: t('刷新', 'Refresh'), icon: <ReloadOutlined />, onClick: () => void loadCmsFields() },
                      { key: 'export', label: t('导出契约', 'Export contract'), icon: <ExportOutlined />, onClick: () => void navigator.clipboard?.writeText(JSON.stringify({ sections: displayedSections, fields: allFields }, null, 2)).then(() => message.success(t('契约 JSON 已复制', 'Contract JSON copied'))) },
                    ])
                  }
                />
              </Space>
            ),
          }))}
        />
        </Spin>
      </ManagementPageBody>

      <Drawer
        title={editingField ? `${t('编辑字段', 'Edit field')} ${editingField.path}` : t('编辑字段', 'Edit field')}
        open={Boolean(editingField)}
        onClose={() => setEditingField(null)}
        width={responsive.isMobile ? '100%' : 560}
        destroyOnHidden
        extra={
          <Button
            icon={<CopyOutlined />}
            onClick={() => void navigator.clipboard?.writeText(editingField?.path || '').then(() => message.success(t('字段路径已复制', 'Field path copied')))}
          >
            {t('复制路径', 'Copy path')}
          </Button>
        }
        footer={
          <Space>
            <Button onClick={() => setEditingField(null)}>{t('取消', 'Cancel')}</Button>
            <Button
              type="primary"
              loading={saving}
              disabled={!editingField || !actionPermission.can(editingField.permission)}
              onClick={() => void saveEditingField()}
            >
              {t('保存草稿', 'Save draft')}
            </Button>
            <Button loading={saving} disabled={!editingField || !actionPermission.can('aiadc:cms:publish')} onClick={() => void publishEditingField()}>
              {t('发布', 'Publish')}
            </Button>
          </Space>
        }
      >
        {editingField ? (
          <Form form={fieldForm} layout="vertical">
            <Descriptions column={1} size="small" bordered>
              <Descriptions.Item label={t('板块', 'Section')}>{editingField.sectionLabel}</Descriptions.Item>
              <Descriptions.Item label={t('位置', 'Location')}>{[editingField.pageKey || editingField.collection, editingField.sectionCode || editingField.area].filter(Boolean).join(' / ')}</Descriptions.Item>
              <Descriptions.Item label={t('字段类型', 'Type')}>{editingField.type}</Descriptions.Item>
              <Descriptions.Item label={t('权限', 'Permission')}>{editingField.permission}</Descriptions.Item>
            </Descriptions>
            <Form.Item name="valueJson" label={editingField.path} required={editingField.required} style={{ marginTop: 16 }}>
              {renderFieldEditor(editingField)}
            </Form.Item>
            {editingField.guarded ? (
              <Typography.Paragraph type="warning">
                {t('这是稳定业务键或路由标识，保存前应二次确认，避免影响前台读取。', 'This is a stable business key or route identifier. Confirm before saving because it affects public reads.')}
              </Typography.Paragraph>
            ) : null}
          </Form>
        ) : null}
      </Drawer>
    </ManagementPage>
  );
};

export default AiadcCmsPage;
