package com.lumira.saas.modules.aiadc.cms.app;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.lumira.common.security.CurrentUser;
import com.lumira.saas.infrastructure.persistence.mybatis.MyBatisQueryOperations;
import com.lumira.saas.modules.aiadc.cms.dto.AiadcCmsDTO;
import com.lumira.saas.modules.aiadc.cms.vo.AiadcCmsVO;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AiadcCmsAppServiceTest {

    private AiadcCmsAppService service;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:aiadc_cms;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("drop table if exists aiadc_cms_content");
        jdbcTemplate.execute("""
                create table aiadc_cms_content (
                  id bigint generated by default as identity primary key,
                  tenant_id bigint not null,
                  section_key varchar(64) not null,
                  section_label varchar(128) not null,
                  page_key varchar(64),
                  collection_key varchar(64),
                  area_key varchar(64),
                  section_code varchar(64),
                  field_path varchar(255) not null,
                  field_type varchar(128) not null,
                  control_type varchar(64) not null,
                  required tinyint not null default 0,
                  editable tinyint not null default 1,
                  guarded tinyint not null default 0,
                  draft_value varchar(20000),
                  published_value varchar(20000),
                  status varchar(32) not null default 'draft',
                  version bigint not null default 1,
                  remark varchar(512),
                  created_by bigint,
                  created_at datetime not null default current_timestamp,
                  updated_by bigint,
                  updated_at datetime not null default current_timestamp,
                  published_by bigint,
                  published_at datetime,
                  deleted tinyint not null default 0,
                  unique (tenant_id, section_key, page_key, collection_key, area_key, section_code, field_path)
                )
                """);
        service = new AiadcCmsAppService(new MyBatisQueryOperations(jdbcTemplate), new ObjectMapper());
    }

    @Test
    void editPublishAndPublicContentExposePublishedFieldsForWebsite() {
        CurrentUser currentUser = currentUser();

        List<AiadcCmsVO.SectionSummary> sections = service.sections(currentUser);
        assertTrue(sections.stream().anyMatch(section -> "site-settings".equals(section.getKey())));

        AiadcCmsDTO.FieldValueRequest request = new AiadcCmsDTO.FieldValueRequest();
        request.setSectionKey("site-settings");
        request.setCollectionKey("siteShell");
        request.setFieldPath("brand.primary");
        request.setValueJson("\"Runtime AIADC\"");
        request.setRemark("website smoke");

        AiadcCmsVO.FieldRecord draft = service.updateField(currentUser, request);
        assertEquals("\"Runtime AIADC\"", draft.getDraftValue());
        assertEquals("draft", draft.getStatus());

        AiadcCmsVO.PublicContent emptyBeforePublish = service.publicContent("zh", "site-settings");
        assertTrue(emptyBeforePublish.getFields().isEmpty());

        AiadcCmsVO.FieldRecord published = service.publishField(currentUser, draft.getId());
        assertEquals("\"Runtime AIADC\"", published.getPublishedValue());
        assertEquals("published", published.getStatus());

        AiadcCmsVO.PublicContent publicContent = service.publicContent("zh", "site-settings");
        assertEquals("zh", publicContent.getLocale());
        assertEquals(1, publicContent.getFields().size());
        assertEquals("brand.primary", publicContent.getFields().get(0).getFieldPath());
        assertEquals(
                "Runtime AIADC",
                publicContent.getValues().get("site-settings.siteShell.root.brand.primary")
        );
    }

    @Test
    void sectionKeyFilterKeepsPublicPayloadScopedForIndependentFrontend() {
        CurrentUser currentUser = currentUser();
        publishValue(currentUser, "site-settings", null, "siteShell", null, null, null, "brand.primary", "\"AIADC\"");
        publishValue(currentUser, "competition-promotion", "home", null, "hero", null, null, "hero.title", "\"Hero\"");

        AiadcCmsVO.PublicContent siteOnly = service.publicContent("zh", "site-settings");

        assertEquals(1, siteOnly.getFields().size());
        assertEquals(Map.of("site-settings.siteShell.root.brand.primary", "AIADC"), siteOnly.getValues());
    }

    private void publishValue(
            CurrentUser currentUser,
            String sectionKey,
            String pageKey,
            String collectionKey,
            String areaKey,
            String sectionCode,
            String unused,
            String fieldPath,
            String valueJson
    ) {
        AiadcCmsDTO.FieldValueRequest request = new AiadcCmsDTO.FieldValueRequest();
        request.setSectionKey(sectionKey);
        request.setPageKey(pageKey);
        request.setCollectionKey(collectionKey);
        request.setAreaKey(areaKey);
        request.setSectionCode(sectionCode);
        request.setFieldPath(fieldPath);
        request.setValueJson(valueJson);
        AiadcCmsVO.FieldRecord draft = service.updateField(currentUser, request);
        service.publishField(currentUser, draft.getId());
    }

    private CurrentUser currentUser() {
        return new CurrentUser(
                2001L,
                "admin",
                1001L,
                "session-1",
                1,
                true,
                Set.of("aiadc:cms:view", "aiadc:cms:update", "aiadc:cms:publish")
        );
    }
}
